Add Saint Patrick's day folder with banner and server icon
python-discord/branding pull request #120
Opened 2021-02-22 20:04 UTC by MrKomodoDragon

I added the assets for st. patrick’s day, which are a banner and server icon. Please let me know if I need to move the files around to different folders. Thank you!

2021-02-22 20:17 UTC, gustavwilliam requested changes
Hi! Thanks for the PR!  This looks great, but there are a few things I'd like to mention.

Seems like there's some weird blue on the banner logo
<img width="330" alt="Screenshot 2021-02-22 at 21 09 52" src="https://user-images.githubusercontent.com/65498475/108764121-796eba80-7552-11eb-8925-843f2cc6e28b.png">

There's also some weird outlines on the server icon:
<img width="133" alt="Screenshot 2021-02-22 at 21 11 25" src="https://user-images.githubusercontent.com/65498475/108764228-9dca9700-7552-11eb-9abc-f0d15c97fcd5.png">
<img width="89" alt="Screenshot 2021-02-22 at 21 12 17" src="https://user-images.githubusercontent.com/65498475/108764255-a6bb6880-7552-11eb-9e3a-c1b1f03d5e41.png">

It seems like this was done using something like Photoshop. I'd recommend Illustrator, Affinity Designer or Inkscape, so you can work directly with the vector shapes. (Ping `Vestergurkan` on the server if you'd like me to explain more).

Considering that the server icon will be tiny, I'm fine with some minor defects in the edges, but if you could go over the edges and see if it can be fixed, that would be awesome! If you are in fact using Photoshop, you can also try out so called "adjustment layers" for modifying only the colors.

Just fix the blue in the banner and I'll be happy this time. Thanks a lot!

2021-02-23 05:20 UTC, MarkKoz commented
If all you need to do is change colours, it's really simple to open the SVG as text and edit the colours. It's very similar to HTML/CSS.

2021-02-23 20:50 UTC, gustavwilliam requested changes
Great to see that you're doing it with Illustrator instead now! A few things:
- Seems like there's one `.DS_Store` left. Could you add that to `.gitignore` so we won't have issues with it being committed in the future?
- It seems like the banner has some weird artifacting. Do you know what might be up? Check it out below:
  <img width="131" alt="Screenshot 2021-02-23 at 21 48 42" src="https://user-images.githubusercontent.com/65498475/108906200-e6e91c80-7620-11eb-9336-e128b7baeb10.png">

Other than that, it's looking pretty good.

2021-02-23 22:44 UTC, MrKomodoDragon commented
I dunno about the artifacting, but will put the .DS_store in .gitignore.

2021-02-23 23:24 UTC, gustavwilliam commented
The banner was previously an sag that only contained an image, which led to the strange artifacting of the fill tool. After discussing this in #media-branding, I've recreated the banner using the colors and dimensions of the original file. Since it seems like an svg can't be uploaded in a GitHub comment, I'll send the file to @MrKomodoDragon over on Discord and he'll export it as a png.

2021-02-24 00:15 UTC, gustavwilliam requested changes
One final thing I'm gonna comment on, unless something changes. The file `events/st_patricks_day/st_patricks_banner (1).svg` should be renamed to `events/st_patricks_day/st_patricks_banner.svg`. Other than that, I've left a single comment for you to check out.

2021-02-24 00:15 UTC, gustavwilliam commented on .gitignore
> +seasonal/evergreen/.DS_Store
```suggestion
.DS_Store
```
This will make it apply to all `.DS_Store`s, instead of just the ones in the specified folder.

2021-02-24 01:06 UTC, gustavwilliam approved these changes
LGTM, thanks! Something seems to make the banner svg very tall, but I don't know what this is about. The shapes are right and it looks (almost) completely right in Illustrator, so I'll approve it. However, if someone knows what could be done about it, I'd love to hear about it.

2021-02-24 06:06 UTC, MarkKoz commented
The banner has a white border all around:

![banner](https://cdn.discordapp.com/attachments/753252897059373066/814014274619441172/banner2.png)

Presumably this is a mistake since none of the other banners are like this. This is what it should be:

![banner](https://user-images.githubusercontent.com/1515135/108955626-5bbd5600-7623-11eb-837a-f2ebd775e4dd.png)

2021-02-24 06:09 UTC, MarkKoz commented
Oh, it seems like exporting from the SVG results in a border but the PNG in this PR looks fine. So only the SVG is messed up.

2021-02-24 18:00 UTC, gustavwilliam commented
@MarkKoz yeah. After digging into this, it seems like the viewbox for the svg was messed up. We fixed it by creating a new artboard in Illustrator and pasting the contents on it. Pretty weird, but it seems to be working now.

2021-02-24 18:18 UTC, lemonsaurus approved these changes
Looks good!

2021-02-24 18:19 UTC, lemonsaurus commented
Thanks @gustavwilliam for the thorough review. Nothing left for me to do here but merge.

2021-02-24 18:19 UTC, merged